import {
  User,
  AttendanceSession,
  AttendanceRecord,
  Assignment,
  AssignmentSubmission,
  EventItem,
  EventRegistration,
  PlacementNotice,
  PlacementApplication,
  NotificationItem,
  AuditLog,
} from "./types";

export const initialUsers: User[] = [
  {
    id: "user-student-1",
    name: "Aarav Sharma",
    email: "aarav.sharma@campus.edu",
    role: "STUDENT",
    department: "Computer Science & Engineering",
    phone: "+91 98765 43210",
    rollNumber: "CS2024-042",
    semester: 6,
    skills: ["React", "TypeScript", "Node.js", "Python", "Docker"],
    bio: "Passionate full-stack developer & AI enthusiast. Building scalable web apps.",
    linkedIn: "https://linkedin.com/in/aarav-sharma",
    gitHub: "https://github.com/aaravsharma",
    resumeUrl: "https://example.com/resumes/aarav-sharma.pdf",
    verified: true,
    createdAt: "2024-08-01T10:00:00Z",
  },
  {
    id: "user-faculty-1",
    name: "Dr. Rajesh Kulkarni",
    email: "rajesh.kulkarni@campus.edu",
    role: "FACULTY",
    department: "Computer Science & Engineering",
    phone: "+91 98123 45678",
    bio: "Professor & Head of AI Research Lab. 15+ years experience in distributed systems.",
    verified: true,
    createdAt: "2022-01-15T09:00:00Z",
  },
  {
    id: "user-coord-1",
    name: "Priya Nair",
    email: "priya.nair@campus.edu",
    role: "COORDINATOR",
    department: "Student Affairs & Event Club",
    phone: "+91 97654 32109",
    bio: "Head Student Affairs & Hackathon Event Coordinator.",
    verified: true,
    createdAt: "2023-05-10T11:30:00Z",
  },
  {
    id: "user-admin-1",
    name: "Administrator (Dean Office)",
    email: "admin@campus.edu",
    role: "ADMIN",
    department: "Administration",
    phone: "+91 99999 00000",
    bio: "System Administrator & Dean of Academic Operations.",
    verified: true,
    createdAt: "2021-01-01T08:00:00Z",
  },
];

export const initialAttendanceSessions: AttendanceSession[] = [
  {
    id: "session-1",
    subject: "Advanced Database Management",
    subjectCode: "CS601",
    facultyId: "user-faculty-1",
    facultyName: "Dr. Rajesh Kulkarni",
    department: "Computer Science",
    date: "2026-08-10",
    timeSlot: "10:00 AM - 11:30 AM",
    qrCodeToken: "QR-DBMS-20260810-8891",
    expiresAt: "2026-08-10T11:45:00Z",
    active: true,
  },
  {
    id: "session-2",
    subject: "Cloud Architecture & DevOps",
    subjectCode: "CS604",
    facultyId: "user-faculty-1",
    facultyName: "Dr. Rajesh Kulkarni",
    department: "Computer Science",
    date: "2026-08-09",
    timeSlot: "02:00 PM - 03:30 PM",
    qrCodeToken: "QR-CLOUD-20260809-4102",
    expiresAt: "2026-08-09T03:45:00Z",
    active: false,
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: "rec-1",
    sessionId: "session-1",
    studentId: "user-student-1",
    studentName: "Aarav Sharma",
    rollNumber: "CS2024-042",
    subject: "Advanced Database Management",
    date: "2026-08-10",
    status: "PRESENT",
    markedAt: "2026-08-10T10:05:12Z",
  },
  {
    id: "rec-2",
    sessionId: "session-2",
    studentId: "user-student-1",
    studentName: "Aarav Sharma",
    rollNumber: "CS2024-042",
    subject: "Cloud Architecture & DevOps",
    date: "2026-08-09",
    status: "PRESENT",
    markedAt: "2026-08-09T14:02:44Z",
  },
];

export const initialAssignments: Assignment[] = [
  {
    id: "assign-1",
    title: "Mini Distributed Storage Engine",
    description: "Design a fault-tolerant key-value store using raft consensus algorithm in Node.js or Go.",
    subject: "Advanced Database Management",
    subjectCode: "CS601",
    facultyId: "user-faculty-1",
    facultyName: "Dr. Rajesh Kulkarni",
    deadline: "2026-08-18T23:59:00Z",
    totalMarks: 100,
    rubrics: [
      "Architecture & Design (30%)",
      "Consensus Implementation (40%)",
      "Test Coverage & Performance (20%)",
      "Code Documentation (10%)",
    ],
    attachments: ["https://campus.edu/resources/cs601-assignment2-spec.pdf"],
    createdAt: "2026-08-01T09:00:00Z",
  },
  {
    id: "assign-2",
    title: "Kubernetes CI/CD Pipeline Automation",
    description: "Build a GitHub Actions workflow deploying a Next.js app to a Minikube cluster with Prometheus monitoring.",
    subject: "Cloud Architecture & DevOps",
    subjectCode: "CS604",
    facultyId: "user-faculty-1",
    facultyName: "Dr. Rajesh Kulkarni",
    deadline: "2026-08-25T23:59:00Z",
    totalMarks: 50,
    rubrics: ["Helm Charts (40%)", "Prometheus Setup (30%)", "Documentation (30%)"],
    createdAt: "2026-08-05T14:00:00Z",
  },
];

export const initialSubmissions: AssignmentSubmission[] = [
  {
    id: "sub-1",
    assignmentId: "assign-1",
    assignmentTitle: "Mini Distributed Storage Engine",
    studentId: "user-student-1",
    studentName: "Aarav Sharma",
    rollNumber: "CS2024-042",
    submissionDate: "2026-08-09T18:22:00Z",
    gitHubUrl: "https://github.com/aaravsharma/kv-store-raft",
    fileUrl: "https://campus.edu/uploads/sub-aarav-kvstore.pdf",
    solutionText: "Implemented raft cluster with 3 node dynamic discovery.",
    status: "GRADED",
    marksObtained: 95,
    feedback: "Exceptional architecture design and clean unit test implementation!",
    plagiarismScore: 2.1,
  },
];

export const initialEvents: EventItem[] = [
  {
    id: "evt-1",
    title: "DevFusion 4.O Hackathon Final Showcase",
    description: "48-hour national level hackathon featuring top AI & Full-Stack solutions across 5 tracks.",
    category: "TECHNICAL",
    banner: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
    venue: "Main Campus Auditorium & Innovation Hub",
    date: "2026-08-20",
    time: "09:00 AM IST",
    registrationDeadline: "2026-08-16T23:59:00Z",
    capacity: 200,
    registeredCount: 164,
    organizer: "Priya Nair (Student Affairs)",
    speakers: ["Dr. Kulkarni", "Sarah Chen (Google DeepMind)", "Alex Rivera (Vercel)"],
    active: true,
  },
  {
    id: "evt-2",
    title: "GenAI & LLM Architecture Masterclass",
    description: "Hands-on workshop on building RAG pipelines, fine-tuning Llama models, and deploying AI agents.",
    category: "WORKSHOP",
    banner: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    venue: "CS Seminar Hall 2",
    date: "2026-08-22",
    time: "02:00 PM IST",
    registrationDeadline: "2026-08-21T18:00:00Z",
    capacity: 120,
    registeredCount: 98,
    organizer: "ACM Student Chapter",
    speakers: ["Dr. Rajesh Kulkarni"],
    active: true,
  },
];

export const initialEventRegistrations: EventRegistration[] = [
  {
    id: "reg-1",
    eventId: "evt-1",
    eventTitle: "DevFusion 4.O Hackathon Final Showcase",
    studentId: "user-student-1",
    studentName: "Aarav Sharma",
    registeredAt: "2026-08-08T11:20:00Z",
    ticketQrCode: "TICKET-EVT1-AARAV-9912",
    status: "CONFIRMED",
  },
];

export const initialPlacements: PlacementNotice[] = [
  {
    id: "place-1",
    companyName: "Google Cloud",
    companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?auto=format&fit=crop&w=120&q=80",
    jobRole: "Software Engineer (Backend / Systems)",
    ctc: "₹ 28.5 LPA",
    location: "Bengaluru / Hyderabad",
    eligibility: "B.Tech CSE/IT, Min CGPA 8.0, 0 Backlogs",
    deadline: "2026-08-25T23:59:00Z",
    description: "Join the Google Cloud core infrastructure engineering group building distributed datastores.",
    requirements: ["C++ / Go / Java", "Data Structures & Algorithms", "System Design fundamentals"],
    postedAt: "2026-08-02T10:00:00Z",
    appliedCount: 42,
  },
  {
    id: "place-2",
    companyName: "Microsoft India",
    companyLogo: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?auto=format&fit=crop&w=120&q=80",
    jobRole: "Full Stack Engineer (Azure AI Platform)",
    ctc: "₹ 26.0 LPA",
    location: "Bengaluru / Noida",
    eligibility: "B.Tech/M.Tech, CGPA 7.5+",
    deadline: "2026-08-30T23:59:00Z",
    description: "Building modern scalable enterprise portal solutions using Next.js, C# .NET, and Azure.",
    requirements: ["TypeScript", "React/Next.js", "C# / Python", "REST APIs"],
    postedAt: "2026-08-05T09:30:00Z",
    appliedCount: 68,
  },
];

export const initialPlacementApplications: PlacementApplication[] = [
  {
    id: "app-1",
    placementId: "place-1",
    companyName: "Google Cloud",
    jobRole: "Software Engineer (Backend / Systems)",
    studentId: "user-student-1",
    studentName: "Aarav Sharma",
    studentEmail: "aarav.sharma@campus.edu",
    resumeUrl: "https://example.com/resumes/aarav-sharma.pdf",
    appliedAt: "2026-08-03T14:10:00Z",
    status: "SHORTLISTED",
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "notif-1",
    userId: "user-student-1",
    title: "New Assignment Published",
    message: "Dr. Rajesh Kulkarni added 'Mini Distributed Storage Engine' due Aug 18.",
    type: "ASSIGNMENT",
    read: false,
    createdAt: "2026-08-10T09:00:00Z",
  },
  {
    id: "notif-2",
    userId: "user-student-1",
    title: "Placement Status Updated",
    message: "Your application for Google Cloud (Software Engineer) was SHORTLISTED!",
    type: "PLACEMENT",
    read: false,
    createdAt: "2026-08-09T16:30:00Z",
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    actorId: "user-admin-1",
    actorName: "Administrator",
    action: "ROLE_UPDATE",
    details: "Granted FACULTY role to user Dr. Rajesh Kulkarni",
    timestamp: "2026-08-08T15:10:00Z",
    ipAddress: "192.168.1.45",
  },
  {
    id: "log-2",
    actorId: "user-faculty-1",
    actorName: "Dr. Rajesh Kulkarni",
    action: "ATTENDANCE_SESSION_CREATED",
    details: "Created QR Session CS601 for DBMS (QR-DBMS-20260810-8891)",
    timestamp: "2026-08-10T10:00:00Z",
    ipAddress: "192.168.1.102",
  },
];
